name: Python package

on: [push, pull_request]

jobs:
  super-lint:
    name: Run Github Super Linter on Full code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code base
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_YAML: true
          VALIDATE_MD: true
          VALIDATE_BASH: true
          VALIDATE_PYTHON: false
          VALIDATE_DOCKER: true
          VALIDATE_ENV: true

  lint:
    name: Run Pylint on code base
    needs: super-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint CLI with pylint
        run: pylint cli/
      - name: Lint GUI with pylint
        run: pylint gui/
